jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      TestProject: ./Test/Test.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Run unit tests
      run: dotnet test $env:TestProject --configuration ${{ matrix.configuration }} --verbosity detailed
