name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: CargoHubTeam2.sln
      TestProject: ./UnitTest/Test.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: dotnet restore $env:Solution_Name

    - name: Build the solution
      run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }}

    - name: Execute unit tests
      run: dotnet test $env:Solution_Name --configuration ${{ matrix.configuration }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build Output
        path: bin\${{ matrix.configuration }}