jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: CargoHubTeam2.sln
      TestProject: ./Test/Test.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear

    - name: Restore dependencies
      run: dotnet restore

    - name: Install required workloads
      run: dotnet workload install microsoft-testplatform

    - name: Build solution
      run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }}

    - name: Run unit tests
      run: dotnet test $env:TestProject --configuration ${{ matrix.configuration }} --no-build --verbosity detailed
